<?php
$global_templating							=	array(
	'{tendoo_version}'				=>	'<?php echo get('core_version');?>',
	'{site_name}'					=>	'<?php echo $options[0]["SITE_NAME"];?>',
	'{site_logo}'					=>	'<?php echo $options[0]["SITE_LOGO"];?>',
	'{menu_loop_start}'				=>	'<?php foreach($controllers as $c)	{ ?>',
	'{menu_loop_end}'				=>	'<?php } ?>',
	'{menu_loop_active_start}'			=>	'<?php if($c["PAGE_CNAME"] == $this->url->controller())	{ ?>',
	'{menu_loop_active_else}'			=>	'<?php } else { ?>',
	'{menu_loop_active_end}'				=>	'<?php } ?>',
	'{menu_loop_islink_start}'			=>	'<?php if($c["PAGE_MODULES"] == "#LINK#")	{ ?>',
	'{menu_loop_islink_else}'			=>	'<?php } else { ?>',
	'{menu_loop_islink_end}'				=>	'<?php } ?>',
	'{menu_loop_submenu}'			=>	'<?php $this->tendoo->getControllerSubmenu($c);?>',
	'{menu_loop_cname}'				=>	'<?php echo $this->url->site_url(array($c["PAGE_CNAME"]));?>',
	'{menu_loop_link}'				=>	'<?php echo $c["PAGE_LINK"];?>',
	'{menu_loop_name}'				=>	'<?php echo ucwords($c["PAGE_NAMES"]);?>',
	'{menu_loop_title}'				=>	'<?php echo $c["PAGE_TITLE"];?>',
	// HEAD
	'{head_title}'					=>	'<?php echo get_page('title');?>',
	'{head_keywords}'				=>	'<?php echo $this->tendoo->getKeywords();?>',
	'{head_description}'			=>	'<?php echo $this->tendoo->getDescription();?>',
	'{head_js_base_tag}'			=>	'<script>
		var site_url	=	"<?php echo $this->url->site_url();?>";
		var base_url	=	"<?php echo $this->url->main_url();?>";
	</script>',
	'{head_css_load}'				=>	'<?php echo $this->file->css_load();?>',
	'{head_js_load}'				=>	'<?php echo $this->file->js_load();?>',
	// HEADER
	'{header_usermenu}'				=>	'<?php echo current_user("menu"); ?>',
    '{header_margin}'				=>	'<?php echo current_user("isconnected") ? \'style="margin-top:30px"\' : \'\';?>',
	// BODY
	'{body_header}'					=>	'<?php echo $header;?>',
	'{body_module_content}'			=>	'<?php echo $module_content;?>',
	'{body_footer}'					=>	'<?php echo $footer;?>',
	'{footer_widgets}'				=>	'<?php $theme->parseBottomWidgets();?>',
	"{site_name}"							=>	"<?php echo \$options[0]['SITE_NAME'];?>",
	"{site_logo}"							=>	"<?php echo \$options[0]['SITE_LOGO'];?>",
	"{page_title}"							=>	"<?php echo \get_page('title');?>",
	"{page_description}"					=>	"<?php echo \$this->tendoo->getDescription();?>",
	"{page_keywords}"						=>	"<?php echo \$this->tendoo->getKeywords();?>",
	"{widgets_right}"						=>	"<?php echo \$this->parseRightWidgets();?>",
	"{widget_right_isset_start}"			=>	"<?php if(count(\$this->ttRightWidgets) > 0){ ?>",
	"{widget_right_isset_end}"				=>	"<?php } ?>",
	"{widget_right_loop_start}"				=>	"<?php foreach(\$this->ttRightWidgets as \$w)		{ ?>",
	"{widget_right_loop_end}"				=>	"<?php } ?>",
	"{widget_right_loop_title}"				=>	"<?php echo \$w['TITLE'];?>",
	"{widget_right_loop_content}"			=>	"<?php echo \$w['CONTENT'];?>",
    "{widgets_left}"						=>  "<?php echo \$this->parseLeftWidgets();?>",
	"{widget_left_isset_start}"				=>	"<?php if(count(\$this->ttLeftWidgets) > 0){ ?>",
	"{widget_left_isset_end}"				=>	"<?php } ?>",
	"{widget_left_loop_start}"				=>	"<?php foreach(\$this->ttLeftWidgets as \$w)		{ ?>",
	"{widget_left_loop_end}"				=>	"<?php } ?>",
	"{widget_left_loop_title}"				=>	"<?php echo \$w['TITLE'];?>",
	"{widget_left_loop_content}"			=>	"<?php echo \$w['CONTENT'];?>",
    "{widgets_bottom}"						=>  "<?php echo \$this->parseBottomWidgets();?>",
	"{widget_bottom_isset_start}"			=>	"<?php if(count(\$this->ttBottomWidgets) > 0){ ?>",
	"{widget_bottom_isset_end}"				=>	"<?php } ?>",
	"{widget_bottom_loop_start}"			=>	"<?php foreach(\$this->ttBottomWidgets as \$w)		{ ?>",
	"{widget_bottom_loop_end}"				=>	"<?php } ?>",
	"{widget_bottom_loop_title}"			=>	"<?php echo \$w['TITLE'];?>",
	"{widget_bottom_loop_content}"			=>	"<?php echo \$w['CONTENT'];?>",
	"{user_isconnected_start}"				=>	"<?php if(current_user('isconnected')){",
	"{user_isconnected_else}"				=>	"<?php } else { ?>",
	"{user_isconnected_end}"				=>	"<?php } ?>",
    "{user_name}"							=>  "<?php echo current_user('name');?>",
	"{user_pseudo}"							=>  "<?php echo current_user('pseudo');?>",
    "{user_email}"							=>	"<?php echo current_user('email');?>",
	"{user_sex}"							=>	"<?php echo current_user('sex');?>",	 
	"{pagination}"							=>  "<?php \$this->parsePagination();?>",
	"{pagination_isset_start}"				=>  "<?php if(is_array(\$this->pagination_datas['innerLink']))	{ ?>",
	"{pagination_isset_else}"				=>  "<?php }	else  { ?>",
	"{pagination_isset_end}"				=>  "<?php } ?>",
	"{pagination_loop_start}"				=>  "<?php foreach(\$this->pagination_datas['innerLink'] as \$p){ ?>",
	"{pagination_loop_end}"					=>  "<?php } ?>",
	"{pagination_loop_active_start}"		=>  "<?php if(\$p['state'] == 'active'){ ?>",
	"{pagination_loop_link}"				=>  "<?php echo \$p['link']; ?>",
	"{pagination_loop_text}"				=>  "<?php echo \$p['text']; ?>",
	"{pagination_loop_active_start}"		=>  "<?php if(\$p['state'] == 'active'){ ?>",
	"{pagination_loop_active_else}"			=>  "<?php }	else { ?>",
	"{pagination_loop_active_end}"			=>  "<?php } ?>",
    "{notice}"								=>  "<?php \$this->parseNotice();?>",
    "{notice_isset_start}"					=>  "<?php if(strlen(\$this->notice->parse_notice()) > 0)	{	?>",
	"{notice_isset_end}"					=>  "<?php	} ?>",
	"{notice_content}"						=>  "<?php \$this->notice->parse_notice();?>",
    "{form}"								=>  "<?php \$this->parseForm();?>",
	"{form_isset_start}"					=>  "<?php	if(count(\$this->currentForm) > 0)		{	?>",
	"{form_isset_end}"						=>  "<?php	} ?>",
	"{form_type}"							=>	"<?php echo \$this->formType;?>",
	"{form_enctype}"						=>  "<?php echo \$this->formEnctype;?>",
	"{form_action}"							=>  "<?php echo \$this->formAction;?>",
	"{form_loop_start_end}"					=>  "<?php foreach(\$this->currentForm as \$c){	echo \$c;} ?>",
// INDEX_PARSE
//	"{index_parseCaroussel}"				// affiche le caroussel_
//	"{index_parseAboutUs}"					// affiche texte descriptif, "A propos de nous"_
//	"{index_parseOnTopContent}"				// affiche les éléménts au top_
//	"{index_parseGalleryShowCase}"			// affiche une gallerie
//	"{index_parseTabShowCase}"				// affiche les éléments sous forme de dossier_
//	"{index_parseTextList}"					// affiche une liste de texte_
//	"{index_parsePartners}"					// affiche information (texte et images) relatives aux partenaires ou assimilés_
	"{index_caroussel_start}" 				=>  "<?php if(count(\$this->carousselElement) > 0)	{ ?>",
	"{index_caroussel_end}" 				=>  "<?php } ?>",
	"{index_caroussel_loop_start}"			=>  "<?php foreach(\$this->carousselElement as \$c)	{	?>",
	"{index_caroussel_loop_end}"			=>  "<?php } ?>",
	"{index_caroussel_loop_title}" 			=>  "<?php echo \$c['LINK'];?>",
	"{index_caroussel_loop_image}" 			=>  "<?php echo \$c['IMAGE'];?>",
	"{index_caroussel_loop_title}" 			=>  "<?php echo \$c['TITLE'];?>",
	/* "{index_caroussel_loop_text[limit]}" 	=>	"<?php echo word_limiter(strip_tags(\$c['CONTENT']),\$limit);?>",*/
//	INDEX_PARSEABOUTUS
		"{index_aboutus_isset_start}" 		=>	"<?php if(isset(\$this->indexAboutUs))	{ ?>",
		"{index_aboutus_isset_end}" 		=>  "<?php } ?>",
		"{index_aboutus_title}"				=>  "<?php echo \$this->indexAboutUsTitle;?>",
		"{index_aboutus_text}" 				=>  "<?php echo (\$this->indexAboutUs);?>",
//	INDEX_LASTESTELEMENTS
    	"{index_le_start}"					=>  "<?php if(count(\$this->lastestElements) > 0){	?>",
        "{index_le_end}"					=>  "<?php 	} ?>",
        "{index_loop_start}"				=>  "<?php foreach(\$this->lastestElements as \$c)	{ \$date	=	\$this->instance->date->time(\$c['DATETIME'],TRUE);	?>",
        "{index_loop_end}"					=>   "<?php } ?>",
        "{index_loop_link}"					=>   "<?php echo \$c['LINK'];?>",
        "{index_loop_thumb}"				=>   "<?php echo \$c['THUMB'];?>",
        "{index_loop_title}"				=>   "<?php echo \$c['TITLE'];?>",
        "{index_loop_datetime}"				=>   "<?php echo \$c['DATETIME'];?>",
        "{index_loop_date_day}"				=>   "<?php echo \$date['d'];?>",
        "{index_loop_date_hour}"			=>   "<?php echo \$date['h'];?>",
        "{index_loop_date_sec}"				=>   "<?php echo \$date['i'];?>",
        "{index_loop_date_year}"			=>   "<?php echo \$date['y'];?>",
        "{index_loop_date_monthfull}"		=>   "<?php echo \$date['month'];?>",
        "{index_loop_date_month}"			=>   "<?php echo \$date['m'];?>",
        "{index_loop_content[limit]}"		=>   "<?php echo word_limiter(strip_tags(\$c['CONTENT']),\$limit);?>",
//	INDEX_ONTOPCONTENT
		"{index_otc_isset_start}" 			=>   "<?php if(count(\$this->onTopContent) > 0){ ?>",
		"{index_otc_isset_end}" 			=>   "<?php } ?>",
		"{index_otc_title}" 				=>   "<?php \$this->onTopContentTitle;?>",
		"{index_otc_loop_start}" 			=>   "<?php foreach(\$this->onTopContent as \$c)	{ ?>",
		"{index_otc_loop_end}" 				=>   "<?php } ?>",
		"{index_otc_loop_link}" 			=>   "<?php echo \$c['LINK'];?>",
		"{index_otc_loop_title}" 			=>   "<?php echo \$c['TITLE'];?>",
		"{index_otc_loop_thumb}" 			=>   "<?php echo \$c['THUMB'];?>",
		"{index_otc_loop_content[limit]}" 	=>   "<?php echo word_limiter(\$c['CARTEGORY'],\$limit);?>",
		"{index_otc_loop_datetime}" 		=>   "<?php echo \$c['DATETIME'];?>",
		// Author
		"{index_otc_loop_author_pseudo}" 	=>   "<?php echo \$c['AUTHOR']['PSEUDO'];?>",
		"{index_otc_loop_author_id}" 		=>   "<?php echo \$c['AUTHOR']['ID'];?>",
		"{index_otc_loop_author_email}" 	=>   "<?php echo \$c['AUTHOR']['EMAIL'];?>",
		"{index_otc_loop_author_thumb}" 	=>   "<?php echo \$c['AUTHOR']['THUMB'];?>",// Tendoo 0_9_8
        "{index_otc_loop_author_profilelink}"		=>	"<?php echo \$this->url->site_url(array('account','profile',\$c['AUTHOR']['PSEUDO']))",
		// category
		"{index_otc_loop_category_loop_start}" 		=>	"<?php foreach(\$c['CATEGORY'] as \$category_child){ ?>",
		"{index_otc_loop_category_loop_end}" 		=>	"<?php };?>",
		"{index_otc_loop_category_link}" 			=>  "<?php echo \$category_child['LINK'];?>",
		"{index_otc_loop_category_text}" 			=>  "<?php echo \$category_child['TEXT'];?>",
//	INDEX_GALLERYSHOWCASE
		"{index_gsc_isset_start}"					=>  "<?php if(count(\$this->galleryGroup) > 0) { ?>",
		"{index_gsc_isset_end}"						=>  "<?php } ;?>",
		"{index_gsc_title}"							=>  "<?php echo \$this->galleryShowCaseTitle;?>",
		"{index_gsc_loop_start}"					=>	"<?php  foreach(\$this->galleryGroup as \$g)    { ?>",
		"{index_gsc_loop_end}"						=>	"<?php  } ?>",
		"{index_gsc_loop_title}"					=>	"<?php echo \$['TITLE'];?>",
		"{index_gsc_loop_full}"						=>	"<?php echo \$['FULL'];?>",
		"{index_gsc_loop_image}"					=>	"<?php echo \$['IMAGE'];?>",
//	INDEX_TABSHOWCASE
		"{index_tsc_isset_start}"					=>   "<?php		if(count(\$this->tabShowCase) > 0)		{	?>",
		"{index_tsc_isset_end}"						=>   "<?php		} ?>",
		"{index_tsc_head_loop_start}"				=>   "<?php	foreach(\$this->tabShowCase as \$s)	{ ?>",
		"{index_tsc_head_loop_end}"					=>   "<?php 		} ?>",
		"{index_tsc_head_loop_title}"				=>   "<?php echo \$s['TITLE'];?>",
		"{index_tsc_head_loop_content}"				=>   "<?php echo \$s['CONTENT'];?>",
		"{index_tsc_body_loop_start}"				=>   "<?php	foreach(\$this->tabShowCase as \$s)	{ ?>",
		"{index_tsc_body_loop_end}"					=>   "<?php 		} ?>",
		"{index_tsc_body_loop_text}"				=>   "<?php echo \$s['CONTENT'];?>",
		"{index_tsc_body_loop_title}"				=>   "<?php echo \$s['TITLE'];?>",
//	INDEX_LISTTEXT
		"{index_lt_isset_start}"					=>   "<?php if(count(\$this->listText) > 0)		{	?>",
		"{index_lt_isset_end}"						=>   "<?php } ?>",
		"{index_lt_title}"							=>   "<?php echo \$this->textListTitle;?>",
		"{index_lt_loop_start}"						=>   "<?php foreach(\$this->listText as \$t)	{	?>",
		"{index_lt_loop_end}"						=>   "<?php } ?>",
		"{index_lt_loop_title}"						=>   "<?php echo \$t['TITLE'];?>",
		"{index_lt_loop_link}"						=>   "<?php echo \$t['LINK'];?>",
		"{index_lt_loop_text[limit]}"				=>   "<?php echo word_limiter(\$t['CONTENT'],\$limit);?>",
//	INDEX_PARTNERS
		"{index_partners_isset_start}"				=>  "<?php		if(isset(\$this->partners_content))		{	?>",
		"{index_partners_isset_end}"				=>  "<?php		} ?>",
		"{index_partners_title}"					=>  "<?php echo \$this->partners_title;?>",
		"{index_partners_text}"						=>  "<?php echo \$this->partners_content;?>",
	"{blog_single}"									=>  "<?php \$this->parseSingleBlogPost();?>",
	"{blog_post}"									=>  "<?php \$this->parseBlogPost();?>",
//    BLOG_POST
    	"{blog_post_isset_start}"					=>  "<?php		if(count(\$this->blogPost) > 0)		{	?>",
        "{blog_post_isset_else}"					=>  "<?php	}		else if(\$this->blogPost === FALSE)		{			?>",
        "{blog_post_isset_end}"						=>  "<?php		} ?>",
        "{blog_post_loop_start}"					=>  "<?php foreach(\$this->blogPost as \$p){	
			\$global	=	\$this->instance->date->time(\$p['TIMESTAMP'],TRUE); 
			\$base		=	\$this->instance->date->time(\$p['TIMESTAMP']);
		?>",
		"{blog_post_loop_end}"						=>  "<?php 		} ?>",
		// Date time
		"{blog_post_loop_time_year}"				=>  "<?php echo \$global['y'];?>",
		"{blog_post_loop_time_month}"				=>  "<?php echo \$global['m'];?>",
		"{blog_post_loop_time_day}"					=>  "<?php echo \$global['d'];?>",
		"{blog_post_loop_time_hour}"				=>  "<?php echo \$global['h'];?>",
		"{blog_post_loop_time_min}"					=>  "<?php echo \$global['i'];?>",
		"{blog_post_loop_time_sec}"					=>  "<?php echo \$global['s'];?>",
		"{blog_post_loop_time_base}"				=>  "<?php echo \$base;?>",
		// End date time
		"{blog_post_loop_link}"						=>  "<?php echo \$p['LINK'];?>",
		"{blog_post_loop_title}"					=>  "<?php echo \$p['TITLE'];?>",
		"{blog_post_loop_full}"						=>  "<?php echo \$p['FULL'];?>",
		"{blog_post_loop_thumb}"					=>  "<?php echo \$p['THUMB'];?>",
		"{blog_post_loop_content[limit]}"			=>  "<?php echo word_limiter(strip_tags(\$p['CONTENT']),50);?>",
		// Categories
		"{blog_post_loop_category_isset_start}"		=>	"<?php if(is_array(\$p['CATEGORIES']) && count(\$p['CATEGORIES']) > 0){ ?>",
		"{blog_post_loop_category_isset_end}"		=>	"<?php } ?>",
		"{blog_post_loop_category_loop_start}"		=>	"<?php foreach(\$p['CATEGORIES'] as \$category_child){ ?>",
        "{blog_post_loop_category_loop_end}"		=>	"<?php } ?>",
        "{blog_post_loop_category_loop_link}"		=>  "<?php echo \$category_child['LINK'];?>",
		"{blog_post_loop_category_loop_title}"		=>  "<?php echo \$category_child['TITLE'];?>",
		"{blog_post_loop_category_loop_description}"=>  "<?php echo \$category_child['DESCRIPTION'];?>",
		// end Categories
		// Keywords
		 "{blog_post_loop_keywords_isset_start}"		=>  "<?php if(is_array(\$p['KEYWORDS']) && count(\$p['KEYWORDS']) > 0){ ?>",
		 "{blog_post_loop_keywords_isset_end}"			=>  "<?php } ?>",
		 "{blog_post_loop_keywords_loop_start}"			=>  "<?php foreach(\$p['KEYWORDS'] as \$keywords){ ?>",
		 "{blog_post_loop_keywords_loop_end}"			=>  "<?php } ?>",
		 "{blog_post_loop_keywords_loop_title}"			=>  "<?php echo \$keywords['TITLE']; ?>",
		 "{blog_post_loop_keywords_loop_description}"	=>  "<?php echo \$keywords['DESCRIPTION']; ?>",
		 "{blog_post_loop_keywords_loop_link}"			=>  "<?php echo \$keywords['LINK']; ?>",
		// end Keywords
		"{blog_post_loop_author_pseudo}"			=>  "<?php echo \$p['AUTHOR']['PSEUDO'];?>",
		"{blog_post_loop_author_id}"				=>  "<?php echo \$p['AUTHOR']['ID'];?>",
		"{blog_post_loop_author_email}"				=>  "<?php echo \$p['AUTHOR']['EMAIL'];?>",
		"{blog_post_loop_author_profilelink}"		=>  "<?php echo \$this->url->site_url(array('account','profile',\$p['AUTHOR']['PSEUDO']));?>",
//	BLOG_SINGLE
    	"{blog_single_isset_start}"					=>  "<?php if(count(\$this->singleBlogPost) > 0)		{	
			\$global	=	\$this->instance->date->time(\$this->singleBlogPost['TIMESTAMP'],TRUE); 
			\$base		=	\$this->instance->date->time(\$this->singleBlogPost['TIMESTAMP']);
		?>",
        "{blog_single_isset_else}"					=>  "<?php		}		else if(\$this->singleBlogPost	===	false)		{			?>",
        "{blog_single_isset_end}"					=>  "<?php 	} ?>",
		// Date time
		"{blog_single_time_year}"					=>  "<?php echo \$global['y'];?>",
		"{blog_single_time_month}"					=>  "<?php echo \$global['m'];?>",
		"{blog_single_time_day}"					=>  "<?php echo \$global['d'];?>",
		"{blog_single_time_hour}"					=>  "<?php echo \$global['h'];?>",
		"{blog_single_time_min}"					=>  "<?php echo \$global['i'];?>",
		"{blog_single_time_sec}"					=>  "<?php echo \$global['s'];?>",
		"{blog_single_time_base}"					=>  "<?php echo \$base;?>",
		// End date time
        "{blog_single_full}"						=>  "<?php echo \$this->singleBlogPost['FULL'];?>",
        "{blog_single_title}"						=>  "<?php echo \$this->singleBlogPost['TITLE'];?>",
        "{blog_single_time}"						=>  "<?php echo \$this->instance->date->time(\$this->singleBlogPost['TIMESTAMP']);?>",
		// Keywords
		 "{blog_single_keywords_isset_start}"				=>  "<?php if(is_array(\$this->singleBlogPost['KEYWORDS']) && count(\$this->singleBlogPost['KEYWORDS']) > 0){ ?>",
		 "{blog_single_keywords_isset_end}"					=>  "<?php } ?>",
		 "{blog_single_keywords_loop_start}"				=>  "<?php foreach(\$this->singleBlogPost['KEYWORDS'] as \$keywords){ ?>",
		 "{blog_single_keywords_loop_end}"					=>  "<?php } ?>",
		 "{blog_single_keywords_loop_title}"				=>  "<?php echo \$keywords['TITLE']; ?>",
		 "{blog_single_keywords_loop_description}"			=>  "<?php echo \$keywords['DESCRIPTION']; ?>",
		 "{blog_single_keywords_loop_link}"					=>  "<?php echo \$keywords['LINK']; ?>",
		// end Keywords
		// Categories
		"{blog_single_category_isset_start"			=>	'<?php if(is_array($this->singleBlogPost["CATEGORIES"]) && count($this->singleBlogPost["CATEGORIES"]) > 0){ ?>',
		"{blog_single_category_isset_end"			=>	'<?php } ?>',
        "{blog_single_category_loop_start}"			=>	"<?php foreach(\$this->singleBlogPost['CATEGORIES'] as \$category_child){ ?>",
		"{blog_single_category_loop_title}"			=>	'<?php echo $category_child[\'TITLE\'];?>',
		"{blog_single_category_loop_link}"			=>	'<?php echo $category_child[\'LINK\'];?>',
		"{blog_single_category_loop_description}"	=>	"<?php echo \$category_child['DESCRIPTION'];?>",
        "{blog_single_category_loop_end}"			=>	"<?php } ?>",
		// En catégories
        "{blog_single_author_profilelink}"			=>  "<?php echo \$this->url->site_url(array('account','profile',\$this->singleBlogPost['AUTHOR']['PSEUDO']));?>",
        "{blog_single_author_pseudo}"				=>  "<?php echo \$this->singleBlogPost['AUTHOR']['PSEUDO'];?>",
        "{blog_single_author_id}"					=>  "<?php echo \$this->singleBlogPost['AUTHOR']['ID'];?>",
        "{blog_single_author_email}"				=>  "<?php echo \$this->singleBlogPost['AUTHOR']['EMAIL'];?>",
        "{blog_single_content}"						=>  "<?php echo \$this->singleBlogPost['CONTENT'];?>",
        "{blog_single_timestamp}"					=>  "<?php echo  \$this->singleBlogPost['TIMESTAMP'];?>",
        "{blog_single_comments_total}"				=>  "<?php echo \$this->TT_SBP_comments;?>",
        "{blog_single_comments_isset_start}"		=>  "<?php	if(\$this->TT_SBP_comments > 0)			{ ?>",
		"{blog_single_comments_isset_else}"			=>  "<?php	} else { ?>",
        "{blog_single_comments_isset_end}"			=>  "<?php	};?>",
        "{blog_single_comments_loop_start}"			=>  "<?php \$commentID	=	1;	foreach(\$this->SBP_comments as \$s)	{ ?>",
		"{blog_single_comments_loop_end}"			=>  "<?php };?>",
        "{blog_single_comments_loop_id}"			=>  "<?php echo \$commentID;?>",
        "{blog_single_comments_loop_author_pseudo}"	=>  "<?php echo \$s['AUTHOR']['PSEUDO'] ;?>",
        "{blog_single_comments_loop_author_id}"		=>  "<?php echo \$s['AUTHOR']['ID'] ;?>",
        "{blog_single_comments_loop_author_email}"	=>  "<?php echo \$s['AUTHOR']['EMAIL'] ;?>",
        "{blog_single_comments_loop_timestamp}"		=>  "<?php echo \$s['TIMESTAMP'];?>",
        "{blog_single_comments_loop_content}"		=>  "<?php echo \$s['CONTENT'];?>",
//		UNIQUE_PARSE
		"{unique_parse}"							=>  "<?php \$this->parseUnique();?>",
//		CONTACT_PARSE
		"{contact_parse}"							=>  "<?php \$this->parseContact();?>",
    	"{contact_title}"							=>  "<?php echo \$this->contactTitle;?>",
    	"{contact_details_isset_start}"				=>  "<?php if(count(\$this->contactAddressItems) > 0)	{	?>",   	
        "{contact_details_isset_end}"				=>  "<?php } ?>",   	
        "{contact_form}"							=>  "<?php \$this->parseForm(\$this->contactHeader['ACTION'],\$this->contactHeader['ENCTYPE'],\$this->contactHeader['METHOD']);?>",
        "{contact_details_loop_start}" 				=>	"<?php	foreach(\$this->contactAddressItems as \$c){	?>",
        "{contact_details_loop_end}"				=>	"<?php } ?>",
        "{contact_details_loop_type}"				=>  "<?php echo \$c['TYPE'];?>",
        "{contact_details_loop_content}"			=>  "<?php echo \$c['CONTENT'];?>",
);
